Require confirmation before deploying to production
trade-tariff/trade-tariff-admin pull request #51
Opened 2021-11-19 10:30 UTC by jebw

### Jira link

HOTT-????

### What?

I have added/removed/altered:

- [ ] Added a confirmation step before deploying to production

### Why?

I am doing this because:

- Currently its not possible to check the app on staging after merging - by the point you are checking it is already deploying to production.

2021-11-19 14:16 UTC, willfish requested changes
Let's talk about this on Monday. This isn't customer facing, has very few users and I hate our process atm. It's slow and antiquated and requires all manner of painful manual QA/gates that I don't really want to replicate.

2021-11-19 14:17 UTC, willfish commented
Ideally, we'd move our other apps to this model rather than the other way around.

2021-11-19 15:00 UTC, jebw commented
I totally agree with that in concept and I'm really keen to look at the plan I proposed for review apps - but as a stop gap this at least makes staging somewhat useful. As it stands staging is worse than useless because it actually slows down deploys through to production. By the point you've got chance to check staging its already busy deploying to prod.

2021-11-19 15:04 UTC, jebw commented
The model used here really only works because because rate of change is so low that we can check on DEV pre-merge, somewhat mitigating the flip flopping issue - if this model gets applied to the main apps without other changes first we'll end up with Madhu discovering QA issues after they've reached our users, potentially hours or days later depending on how busy he is.

2021-11-23 10:04 UTC, willfish approved these changes
On the basis that the coverage is naff let's move this in

2021-12-01 11:44 UTC, merged