GL-370: Add admin UI to List pseudo measures
trade-tariff/trade-tariff-admin pull request #719
Opened 2024-05-23 14:40 UTC by rasikasri

### Jira link

[GL-495](https://transformuk.atlassian.net/browse/GL-370)

### What?

I have added/removed/altered:

- [ ] Added admin UL to list green lanes measures

### Why?

I am doing this because:

- Admin user should be able to manage green lanes measures

2024-05-30 15:57 UTC, jebw requested changes
Looks good - couple of small amends to the html page

2024-05-30 15:57 UTC, jebw commented on app/views/green_lanes/measures/index.html.erb
> +          <%= me.goods_nomenclature.goods_nomenclature_item_id if me.goods_nomenclature.present?%>
You can use the safe navigation operator here instead of the `if` condition

```
<%= me.goods_nomenclature&.goods_nomenclature_item_id %>
```

2024-05-30 15:57 UTC, jebw commented on app/views/green_lanes/measures/index.html.erb
> +          <%= me.category_assessment&.theme&.code if me.category_assessment.present? && category_assessment.theme.present?%>
`if` condition is superfluous - safe navigation operator measns its not needed - also the second condition looks wrong?

2024-05-30 15:57 UTC, jebw commented on app/views/green_lanes/measures/index.html.erb
> +          <%= me.category_assessment.measure_type_id if me.category_assessment.present?%>
just safe navigation `me.category_assessment&.measure_type_id`

2024-05-30 15:57 UTC, jebw commented on app/views/green_lanes/measures/index.html.erb
> +          <%= me.category_assessment.regulation_id if me.category_assessment.present?%>
`me.category_assessment&.regulation_id`

2024-06-18 16:44 UTC, shjohnson submitted a review, later dismissed
Happy to approve but would be good to add in the safe navigation stuff

2024-06-21 15:07 UTC, willfish approved these changes

2024-06-21 15:09 UTC, merged